before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
language: node_js
node_js:
  - "node"
dist: trusty
sudo: required
install:
  - yarn config set workspaces-experimental true
  - yarn
os:
  - linux
script:
  - yarn test
